### PR TITLE
add dockerfile

### PR DESCRIPTION
**Pull request by anysoft**
# build docker image
```
docker build -t aliyun-auto-signin .
```

# run docker
```
docker run --name aliyun-auto-signin -v /root/config.ini:/apps/aliyun-auto-signin/config.ini -d aliyun-auto-signin
```

`/root/config.ini` is the path of your config file
you can add it into README.MD

@ImYrS

### CODE REVIEW

**Comment by ImYrS** [comment]
@anysoft I have updated the readme to include usages for using Docker. Could you please review it and let me know if there are any errors? Thanks for help.

**Comment by anysoft** [comment]
I followed your steps and tried it out, everything worked fine

> @anysoft I have updated the readme to include usages for using Docker. Could you please review it and let me know if there are any errors? Thanks for help.

everything worked fine! :)

**Comment by ImYrS** [comment]
Great! I will add the compose file to the readme later.

**Comment by 17huiwei** [comment]
how to update when github update?

**Comment by ImYrS** [comment]
@17huiwei if you are using GitHub actions, it’ll use the latest release version automatically.

**Pull request merged**
